### ISSUE TITLE
Wrong installation URL?

### ISSUE THREAD

**Issue by juj** [OpenDroneMap/LiveODM#10]
Getting Started guide lists git clone URL

git clone https://github.com/manand881/LiveODM.git

should that instead be

git clone https://github.com/OpenDroneMap/LiveODM.git

?

**Comment by pierotofy** [comment]
Nice catch!

I've fixed it in https://github.com/OpenDroneMap/LiveODM/commit/c7715a82b302a1325c98618d961aa4e66ed3fa93

Thanks for the report! :pray:
